CREATE DATABASE BACSIHAY
GO

USE BACSIHAY

GO

CREATE TABLE BACSI(
	ID_BS INT IDENTITY PRIMARY KEY,
	TEN_BS NVARCHAR(50) NOT NULL,
	TUOI_BS INT,
	GT_BS INT	CHECK (GT_BS IN ('1','0')),
	NLV_BS	NVARCHAR(50) NOT NULL,
	NKB_BS	NVARCHAR(50) NOT NULL,
	SDT_BS	INT,
	Email_BS NVARCHAR NOT NULL,
	Loai INT DEFAULT(1),
)

CREATE TABLE NGUOIDUNG(
	ID_ND INT IDENTITY PRIMARY KEY,
	TEN_ND NVARCHAR(50) NOT NULL,
	TUOI_ND INT,
	GT_ND INT	CHECK (GT_ND IN ('1','0')),
	DC_ND	NVARCHAR(50) NOT NULL,
	SDT_ND	INT,
	Email_ND NVARCHAR NOT NULL,
	Loai INT DEFAULT(2),
)

CREATE TABLE LICHDANGKY(
	ID INT IDENTITY PRIMARY KEY,
	ID_BS INT REFERENCES BACSI(ID_BS),
	Ngay DATE,
	DSKB NVARCHAR,
)

CREATE TABLE NHOMKHAMBENH(
	ID INT IDENTITY PRIMARY KEY,
	Thoi_gian DATETIME, 
	So_luong INT,
	DSDK NVARCHAR,
)

CREATE TABLE DANHGIA(
	ID_BS INT REFERENCES BACSI(ID_BS) NOT NULL,
	ID_ND INT REFERENCES NGUOIDUNG(ID_ND) NOT NULL,
	DG_ND NVARCHAR(500),
)
	
CREATE TABLE THUOC(
	ID_THUOC INT IDENTITY PRIMARY KEY,
	TEN_THUOC NVARCHAR(50) NOT NULL, 
	TAC_DUNG NVARCHAR(50) NOT NULL, 
	CHONG_CD NVARCHAR(50) NOT NULL, 
)

CREATE TABLE DONTHUOC(
	ID_DON_THUOC INT IDENTITY PRIMARY KEY,
	ID_THUOC INT REFERENCES THUOC(ID_THUOC) NOT NULL,
	HDSD NVARCHAR(50) NOT NULL, 
	SO_LUONG NVARCHAR(50) NOT NULL, 
)

CREATE TABLE LICHSUKHAM(
	THOI_GIAN DATETIME,
	ID_BS INT REFERENCES BACSI(ID_BS) NOT NULL,
	ID_BN INT REFERENCES NGUOIDUNG(ID_ND) NOT NULL,
	ID_DON_THUOC INT REFERENCES DONTHUOC(ID_DON_THUOC) NOT NULL,
)
